### ISSUE TITLE
Multiple file selection

### ISSUE THREAD

**Issue by Anton-Samarskyi** [spookygames/gdx-nativefilechooser#11]
Is there plans to provide possibility to select multiple files?
Is what I see, it's possible, but requires changes in `NativeFileChooserCallback` (probably, another method should be added, like onFile**s**Chosen that should handle multiple files).

**Comment by arthurtemple** [comment]
This feature is now available in [version 2.4.0](https://github.com/spookygames/gdx-nativefilechooser/releases/tag/2.4.0).
