### ISSUE TITLE
Are you planning on adding savedialog for File chooser?

### ISSUE THREAD

**Issue by serifpersia** [spookygames/gdx-nativefilechooser#4]
I'm re writing my swing app to libgdx. Loading a file works nice with your lib but I can't find anywhere how to open file chooser and save file. In swing we had funcs for save and load dialog file chooser.

Might try to create something like this with chatgpt's help. A starting point would be a huge help

**Comment by SimonIT** [comment]
Maybe an option in the `NativeFileChooserConfiguration` for toggling between opening and saving? What's your opinion @arthurtemple ?

**Comment by arthurtemple** [comment]
This library was developed with file _opening_ in mind and the idea of _saving_ files never occurred before now.

I think implementations other than swing could also benefit from this feature. And in this case, I would rather see split methods ([obligatory Martin Fowler post](https://martinfowler.com/bliki/FlagArgument.html)).

No time to see to it right now, but next week I could take a look.

PRs welcome of course!

**Comment by serifpersia** [comment]
> This library was developed with file _opening_ in mind and the idea of _saving_ files never occurred before now.
> 
> I think implementations other than swing could also benefit from this feature. And in this case, I would rather see split methods ([obligatory Martin Fowler post](https://martinfowler.com/bliki/FlagArgument.html)).
> 
> No time to see to it right now, but next week I could take a look.
> 
> PRs welcome of course!

Nice. I stopped working on my app since I can't save profile :)

**Comment by arthurtemple** [comment]
New version 2.2.0 features a saving option (desktop-only).

Please follow the example in the README for hints, and let me know if there is any issue.
