### ISSUE TITLE
MimeFilter and FilenameFilter not applied

### ISSUE THREAD

**Issue by belchianbeer** [spookygames/gdx-nativefilechooser#5]
Hi,

was following the instructions from your site and neither the mime filter nor the FilenameFilter could be applied. The title however is applied. Another strange observed abnormality is that the accept() method of the FilenameFilter is executed several times.

Best regards,
Lukas
![Screenshot 2023-06-16 133542](https://github.com/spookygames/gdx-nativefilechooser/assets/22379665/faf2c0e8-f55e-4dc7-83df-5c2ecd2611b4)
![Screenshot 2023-06-16 133642](https://github.com/spookygames/gdx-nativefilechooser/assets/22379665/149f1f54-63bb-4d68-9862-7ebdc297b5f7)

**Comment by arthurtemple** [comment]
Thanks for the feedback. For additional context, you are using the desktop (AWT) implementation if I'm not wrong.

For the `FilenameFilter` to be called several times is expected: it is to be called once per file encountered in the directory.
You could log the file names to confirm that.

**Comment by belchianbeer** [comment]
Yes, I am using the desktop implementation (implementation 'games.spooky.gdx:gdx-nativefilechooser-desktop:2.1.0')
I am also using: sourceCompatibility = JavaVersion.VERSION_1_8 inside desktop build.gradle
and SDK: temurin-1.8.0_372
