### ISSUE TITLE
Choose directory

### ISSUE THREAD

**Issue by aliyildiz1980** [spookygames/gdx-nativefilechooser#6]
Hi,

Are you planning to implement choosing directory?

Regards

**Comment by arthurtemple** [comment]
Hello,
Thanks for your interest in this project!
Directory choosing is not planned because the need for this feature has never been expressed before. But this looks perfectly doable indeed.
Cheers

**Comment by quangvuduc** [comment]
Hi @arthurtemple, it's been so long since this issues opened. But any chance, will it be implemented?

**Comment by arthurtemple** [comment]
This feature is now available in [version 2.4.0](https://github.com/spookygames/gdx-nativefilechooser/releases/tag/2.4.0).
