### ISSUE TITLE
DesktopFileChooser does not release resouces used by fileDialog

### ISSUE THREAD

**Issue by Anton-Samarskyi** [spookygames/gdx-nativefilechooser#9]
I tried to use DesktopFileChooser in my app and noticed that some thread is still present after application is closed. I figured out that it's due to missing dispose call on fileDialog in DesktopFileChooser.

The fix looks pretty simple (I checked it locally):
`fileDialog.dispose();`
But better to do that in finally block.

**Comment by Anton-Samarskyi** [comment]
Please take a look:
https://github.com/spookygames/gdx-nativefilechooser/pull/10

**Comment by arthurtemple** [comment]
Thanks a lot for your contribution!

The issue is fixed in [version 2.4.0](https://github.com/spookygames/gdx-nativefilechooser/releases/tag/2.4.0).
